//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/MyAsset/Script/Input/Input_Basic.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input_Basic: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input_Basic()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input_Basic"",
    ""maps"": [
        {
            ""name"": ""Base"",
            ""id"": ""b267d258-d06d-4f73-8017-783427c6fc93"",
            ""actions"": [
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""ead18ff9-19f9-4c0f-9fcb-9b2111f225a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Controller_MoveAxis"",
                    ""type"": ""Value"",
                    ""id"": ""93792c85-ae0a-493c-920a-aab599894c65"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Controller_LookAxis"",
                    ""type"": ""Value"",
                    ""id"": ""2263c5bf-ea2c-40e5-9c4b-693862707bac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Main_Button"",
                    ""type"": ""Button"",
                    ""id"": ""5ed09253-5ee9-41f0-b568-1655f17a383b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action_Button"",
                    ""type"": ""Button"",
                    ""id"": ""88d91bc6-35e8-4e0c-9397-d51c6c2732f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sub_Button"",
                    ""type"": ""Button"",
                    ""id"": ""90f74e08-d61f-4c19-a90d-758d6ce934a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Utility_Button"",
                    ""type"": ""Button"",
                    ""id"": ""d1d72049-7d99-4ce3-881d-ab44be88172d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Extra_1_Button"",
                    ""type"": ""Button"",
                    ""id"": ""5f4c9cb1-dd35-4ad2-8d9a-e611ac157e4b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Extra_2_Button"",
                    ""type"": ""Button"",
                    ""id"": ""6582c544-4864-4617-8652-f626dfcf2250"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu_Button"",
                    ""type"": ""Button"",
                    ""id"": ""a19c0758-1f16-4937-9f63-1cfefd82a902"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SubMenu_Button"",
                    ""type"": ""Button"",
                    ""id"": ""e11ee433-043c-4654-9a74-45a065ed1ec1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugCMD_Reload"",
                    ""type"": ""Button"",
                    ""id"": ""7074b6be-25b4-433d-a88c-274c3bf2b612"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugCMD_Death"",
                    ""type"": ""Button"",
                    ""id"": ""4262a017-6b50-4e50-8f06-64e385205bc7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugCMD_ClearAll"",
                    ""type"": ""Button"",
                    ""id"": ""88e878bd-6338-418b-b368-af4cff1ec3a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d76b9d1-7d5a-4188-98df-b06c16a0570f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebf89ced-a4db-4bed-84f3-b7ef24fcba0a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keybind"",
                    ""id"": ""338da0f2-13e4-4773-8173-a3af49f6614e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""496280eb-5b65-4f88-a0eb-0cfe9cf4d483"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""112d72dc-7b3b-461c-bca5-97252bc97b45"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2845ff48-a2c7-4e17-98cd-08f4db78912d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""53e91ca2-296f-4252-8400-c8a5585402f8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left Pad"",
                    ""id"": ""3ef9bd51-dac7-485f-8483-a6a73474f656"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""de95f36e-6c14-4b00-9221-85f8fcd224e3"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""06f7ac1b-21cc-458d-b50b-dbf377a31776"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a94ba533-e026-4d96-894e-416b463f67c4"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""16aa464d-22e3-44e6-ac15-106b53ce5437"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_MoveAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0cb73068-60ea-4dec-8da7-cb45854555e0"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Main_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bbb32ca-f77b-48cf-a83f-e704e9a747ff"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Main_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56f9e9e2-ad8a-4110-ba14-c50261948f01"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2359f03a-3b2e-4be8-a9df-109c2c1b27aa"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3b9bf56-de42-49e9-8f14-09d7e2fae8cb"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sub_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56716079-06fb-46ac-b6bd-1f61b5e37eef"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sub_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9e37965-ef18-4b82-ad6a-09b9ec2ea418"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab9224c6-b4fb-48db-9950-9a35f054c98e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaa2fa1b-9277-4ff5-9f78-5bbf73e6b2fd"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Utility_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70850877-e284-470d-8870-7e5c48b86541"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Extra_1_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02f628ed-b606-44cf-8456-79b8d5e2a6bf"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Extra_1_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""438259a8-998e-4d4b-964d-186bc4ad0405"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Extra_2_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbf9ff6f-2847-428c-8400-2744a4dd2137"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Extra_2_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ddeef8b3-ebd5-4191-9b02-685058a1b611"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e89b79fd-dfc2-4d8f-a56a-038fe6361bb9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a76ccfd8-f04d-47e5-8a06-bd9d7694809a"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubMenu_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c802588d-9fdf-4c74-819b-92e7acd814d9"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubMenu_Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b038acd0-5b7d-4e1a-849f-f50aa944bbac"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_LookAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""759337af-c1a3-40c2-86f1-cd65c40a64a6"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controller_LookAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d3dba8e-cbcc-4e61-9005-dc6a857c77e0"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugCMD_Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8da2d3bb-2952-41a8-a892-e90e2200efe6"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugCMD_Death"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""495a7b66-d1c6-41d4-8bae-13db2c1e3b37"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugCMD_ClearAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Base
        m_Base = asset.FindActionMap("Base", throwIfNotFound: true);
        m_Base_CursorPosition = m_Base.FindAction("CursorPosition", throwIfNotFound: true);
        m_Base_Controller_MoveAxis = m_Base.FindAction("Controller_MoveAxis", throwIfNotFound: true);
        m_Base_Controller_LookAxis = m_Base.FindAction("Controller_LookAxis", throwIfNotFound: true);
        m_Base_Main_Button = m_Base.FindAction("Main_Button", throwIfNotFound: true);
        m_Base_Action_Button = m_Base.FindAction("Action_Button", throwIfNotFound: true);
        m_Base_Sub_Button = m_Base.FindAction("Sub_Button", throwIfNotFound: true);
        m_Base_Utility_Button = m_Base.FindAction("Utility_Button", throwIfNotFound: true);
        m_Base_Extra_1_Button = m_Base.FindAction("Extra_1_Button", throwIfNotFound: true);
        m_Base_Extra_2_Button = m_Base.FindAction("Extra_2_Button", throwIfNotFound: true);
        m_Base_Menu_Button = m_Base.FindAction("Menu_Button", throwIfNotFound: true);
        m_Base_SubMenu_Button = m_Base.FindAction("SubMenu_Button", throwIfNotFound: true);
        m_Base_DebugCMD_Reload = m_Base.FindAction("DebugCMD_Reload", throwIfNotFound: true);
        m_Base_DebugCMD_Death = m_Base.FindAction("DebugCMD_Death", throwIfNotFound: true);
        m_Base_DebugCMD_ClearAll = m_Base.FindAction("DebugCMD_ClearAll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Base
    private readonly InputActionMap m_Base;
    private List<IBaseActions> m_BaseActionsCallbackInterfaces = new List<IBaseActions>();
    private readonly InputAction m_Base_CursorPosition;
    private readonly InputAction m_Base_Controller_MoveAxis;
    private readonly InputAction m_Base_Controller_LookAxis;
    private readonly InputAction m_Base_Main_Button;
    private readonly InputAction m_Base_Action_Button;
    private readonly InputAction m_Base_Sub_Button;
    private readonly InputAction m_Base_Utility_Button;
    private readonly InputAction m_Base_Extra_1_Button;
    private readonly InputAction m_Base_Extra_2_Button;
    private readonly InputAction m_Base_Menu_Button;
    private readonly InputAction m_Base_SubMenu_Button;
    private readonly InputAction m_Base_DebugCMD_Reload;
    private readonly InputAction m_Base_DebugCMD_Death;
    private readonly InputAction m_Base_DebugCMD_ClearAll;
    public struct BaseActions
    {
        private @Input_Basic m_Wrapper;
        public BaseActions(@Input_Basic wrapper) { m_Wrapper = wrapper; }
        public InputAction @CursorPosition => m_Wrapper.m_Base_CursorPosition;
        public InputAction @Controller_MoveAxis => m_Wrapper.m_Base_Controller_MoveAxis;
        public InputAction @Controller_LookAxis => m_Wrapper.m_Base_Controller_LookAxis;
        public InputAction @Main_Button => m_Wrapper.m_Base_Main_Button;
        public InputAction @Action_Button => m_Wrapper.m_Base_Action_Button;
        public InputAction @Sub_Button => m_Wrapper.m_Base_Sub_Button;
        public InputAction @Utility_Button => m_Wrapper.m_Base_Utility_Button;
        public InputAction @Extra_1_Button => m_Wrapper.m_Base_Extra_1_Button;
        public InputAction @Extra_2_Button => m_Wrapper.m_Base_Extra_2_Button;
        public InputAction @Menu_Button => m_Wrapper.m_Base_Menu_Button;
        public InputAction @SubMenu_Button => m_Wrapper.m_Base_SubMenu_Button;
        public InputAction @DebugCMD_Reload => m_Wrapper.m_Base_DebugCMD_Reload;
        public InputAction @DebugCMD_Death => m_Wrapper.m_Base_DebugCMD_Death;
        public InputAction @DebugCMD_ClearAll => m_Wrapper.m_Base_DebugCMD_ClearAll;
        public InputActionMap Get() { return m_Wrapper.m_Base; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BaseActions set) { return set.Get(); }
        public void AddCallbacks(IBaseActions instance)
        {
            if (instance == null || m_Wrapper.m_BaseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BaseActionsCallbackInterfaces.Add(instance);
            @CursorPosition.started += instance.OnCursorPosition;
            @CursorPosition.performed += instance.OnCursorPosition;
            @CursorPosition.canceled += instance.OnCursorPosition;
            @Controller_MoveAxis.started += instance.OnController_MoveAxis;
            @Controller_MoveAxis.performed += instance.OnController_MoveAxis;
            @Controller_MoveAxis.canceled += instance.OnController_MoveAxis;
            @Controller_LookAxis.started += instance.OnController_LookAxis;
            @Controller_LookAxis.performed += instance.OnController_LookAxis;
            @Controller_LookAxis.canceled += instance.OnController_LookAxis;
            @Main_Button.started += instance.OnMain_Button;
            @Main_Button.performed += instance.OnMain_Button;
            @Main_Button.canceled += instance.OnMain_Button;
            @Action_Button.started += instance.OnAction_Button;
            @Action_Button.performed += instance.OnAction_Button;
            @Action_Button.canceled += instance.OnAction_Button;
            @Sub_Button.started += instance.OnSub_Button;
            @Sub_Button.performed += instance.OnSub_Button;
            @Sub_Button.canceled += instance.OnSub_Button;
            @Utility_Button.started += instance.OnUtility_Button;
            @Utility_Button.performed += instance.OnUtility_Button;
            @Utility_Button.canceled += instance.OnUtility_Button;
            @Extra_1_Button.started += instance.OnExtra_1_Button;
            @Extra_1_Button.performed += instance.OnExtra_1_Button;
            @Extra_1_Button.canceled += instance.OnExtra_1_Button;
            @Extra_2_Button.started += instance.OnExtra_2_Button;
            @Extra_2_Button.performed += instance.OnExtra_2_Button;
            @Extra_2_Button.canceled += instance.OnExtra_2_Button;
            @Menu_Button.started += instance.OnMenu_Button;
            @Menu_Button.performed += instance.OnMenu_Button;
            @Menu_Button.canceled += instance.OnMenu_Button;
            @SubMenu_Button.started += instance.OnSubMenu_Button;
            @SubMenu_Button.performed += instance.OnSubMenu_Button;
            @SubMenu_Button.canceled += instance.OnSubMenu_Button;
            @DebugCMD_Reload.started += instance.OnDebugCMD_Reload;
            @DebugCMD_Reload.performed += instance.OnDebugCMD_Reload;
            @DebugCMD_Reload.canceled += instance.OnDebugCMD_Reload;
            @DebugCMD_Death.started += instance.OnDebugCMD_Death;
            @DebugCMD_Death.performed += instance.OnDebugCMD_Death;
            @DebugCMD_Death.canceled += instance.OnDebugCMD_Death;
            @DebugCMD_ClearAll.started += instance.OnDebugCMD_ClearAll;
            @DebugCMD_ClearAll.performed += instance.OnDebugCMD_ClearAll;
            @DebugCMD_ClearAll.canceled += instance.OnDebugCMD_ClearAll;
        }

        private void UnregisterCallbacks(IBaseActions instance)
        {
            @CursorPosition.started -= instance.OnCursorPosition;
            @CursorPosition.performed -= instance.OnCursorPosition;
            @CursorPosition.canceled -= instance.OnCursorPosition;
            @Controller_MoveAxis.started -= instance.OnController_MoveAxis;
            @Controller_MoveAxis.performed -= instance.OnController_MoveAxis;
            @Controller_MoveAxis.canceled -= instance.OnController_MoveAxis;
            @Controller_LookAxis.started -= instance.OnController_LookAxis;
            @Controller_LookAxis.performed -= instance.OnController_LookAxis;
            @Controller_LookAxis.canceled -= instance.OnController_LookAxis;
            @Main_Button.started -= instance.OnMain_Button;
            @Main_Button.performed -= instance.OnMain_Button;
            @Main_Button.canceled -= instance.OnMain_Button;
            @Action_Button.started -= instance.OnAction_Button;
            @Action_Button.performed -= instance.OnAction_Button;
            @Action_Button.canceled -= instance.OnAction_Button;
            @Sub_Button.started -= instance.OnSub_Button;
            @Sub_Button.performed -= instance.OnSub_Button;
            @Sub_Button.canceled -= instance.OnSub_Button;
            @Utility_Button.started -= instance.OnUtility_Button;
            @Utility_Button.performed -= instance.OnUtility_Button;
            @Utility_Button.canceled -= instance.OnUtility_Button;
            @Extra_1_Button.started -= instance.OnExtra_1_Button;
            @Extra_1_Button.performed -= instance.OnExtra_1_Button;
            @Extra_1_Button.canceled -= instance.OnExtra_1_Button;
            @Extra_2_Button.started -= instance.OnExtra_2_Button;
            @Extra_2_Button.performed -= instance.OnExtra_2_Button;
            @Extra_2_Button.canceled -= instance.OnExtra_2_Button;
            @Menu_Button.started -= instance.OnMenu_Button;
            @Menu_Button.performed -= instance.OnMenu_Button;
            @Menu_Button.canceled -= instance.OnMenu_Button;
            @SubMenu_Button.started -= instance.OnSubMenu_Button;
            @SubMenu_Button.performed -= instance.OnSubMenu_Button;
            @SubMenu_Button.canceled -= instance.OnSubMenu_Button;
            @DebugCMD_Reload.started -= instance.OnDebugCMD_Reload;
            @DebugCMD_Reload.performed -= instance.OnDebugCMD_Reload;
            @DebugCMD_Reload.canceled -= instance.OnDebugCMD_Reload;
            @DebugCMD_Death.started -= instance.OnDebugCMD_Death;
            @DebugCMD_Death.performed -= instance.OnDebugCMD_Death;
            @DebugCMD_Death.canceled -= instance.OnDebugCMD_Death;
            @DebugCMD_ClearAll.started -= instance.OnDebugCMD_ClearAll;
            @DebugCMD_ClearAll.performed -= instance.OnDebugCMD_ClearAll;
            @DebugCMD_ClearAll.canceled -= instance.OnDebugCMD_ClearAll;
        }

        public void RemoveCallbacks(IBaseActions instance)
        {
            if (m_Wrapper.m_BaseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBaseActions instance)
        {
            foreach (var item in m_Wrapper.m_BaseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BaseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BaseActions @Base => new BaseActions(this);
    public interface IBaseActions
    {
        void OnCursorPosition(InputAction.CallbackContext context);
        void OnController_MoveAxis(InputAction.CallbackContext context);
        void OnController_LookAxis(InputAction.CallbackContext context);
        void OnMain_Button(InputAction.CallbackContext context);
        void OnAction_Button(InputAction.CallbackContext context);
        void OnSub_Button(InputAction.CallbackContext context);
        void OnUtility_Button(InputAction.CallbackContext context);
        void OnExtra_1_Button(InputAction.CallbackContext context);
        void OnExtra_2_Button(InputAction.CallbackContext context);
        void OnMenu_Button(InputAction.CallbackContext context);
        void OnSubMenu_Button(InputAction.CallbackContext context);
        void OnDebugCMD_Reload(InputAction.CallbackContext context);
        void OnDebugCMD_Death(InputAction.CallbackContext context);
        void OnDebugCMD_ClearAll(InputAction.CallbackContext context);
    }
}
